# Start builder
#####################################################
FROM node:13.8.0 as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run ng build -- --prod --output-path=dist

# Production Run Phase
#####################################################
FROM nginx:1.17.8-alpine

EXPOSE 8080

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

RUN adduser -S -H -g "" -G www-data www-data

RUN touch /var/run/nginx.pid && \
    chown -R www-data:www-data /var/run/nginx.pid && \
    chown -R www-data:www-data /var/cache/nginx

USER www-data